CREATE OR REPLACE VIEW test_1
FOLDER = '/dervived_view' AS
SELECT 1 AS ID, 'Test Value 1' AS DESCRIPTION
UNION
SELECT 2 AS ID, 'Test Value 2' AS DESCRIPTION;

CREATE OR REPLACE VIEW test_2
FOLDER = '/dervived_view' AS
SELECT 3 AS ID, 'Test Value 3' AS DESCRIPTION
UNION
SELECT 4 AS ID, 'Test Value 4' AS DESCRIPTION;